"""Canonical intent labels for CEP inbox routing."""

from __future__ import annotations

INTENTS = (
    "pre_purchase",
    "order_status",
    "post_purchase_issue",
    "non_customer_noise",
)

INTENT_DESCRIPTIONS = {
    "pre_purchase": "Product, price, stock, shipping policy questions before buying",
    "order_status": "Where is my order, tracking, ETA, delivery updates",
    "post_purchase_issue": "Returns, refunds, damaged/wrong item, cancel after order",
    "non_customer_noise": "Spam, stickers, ok/thanks-only, empty, unrelated chatter",
}

# Bitext retail intent → our 4 buckets
BITEXT_TO_INTENT: dict[str, str] = {
    # pre-purchase
    "product_information": "pre_purchase",
    "availability": "pre_purchase",
    "availability_online": "pre_purchase",
    "availability_in_store": "pre_purchase",
    "add_product": "pre_purchase",
    "remove_product": "pre_purchase",
    "payment_methods": "pre_purchase",
    "pay": "pre_purchase",
    "shipping_costs": "pre_purchase",
    "submit_product_idea": "pre_purchase",
    "submit_product_feedback": "pre_purchase",
    # order status
    "track_order": "order_status",
    "track_delivery": "order_status",
    "delivery_time": "order_status",
    "order_history": "order_status",
    "request_invoice": "order_status",
    # post-purchase issues
    "cancel_order": "post_purchase_issue",
    "change_order": "post_purchase_issue",
    "delivery_issue": "post_purchase_issue",
    "damaged_delivery": "post_purchase_issue",
    "missing_item": "post_purchase_issue",
    "wrong_item": "post_purchase_issue",
    "product_issue": "post_purchase_issue",
    "exchange_product": "post_purchase_issue",
    "exchange_product_in_store": "post_purchase_issue",
    "return_product": "post_purchase_issue",
    "return_product_online": "post_purchase_issue",
    "return_product_in_store": "post_purchase_issue",
    "return_policy": "post_purchase_issue",
    "refund_policy": "post_purchase_issue",
    "refund_status": "post_purchase_issue",
    "request_refund": "post_purchase_issue",
    "payment_issue": "post_purchase_issue",
    "submit_feedback": "post_purchase_issue",
    "technical_issue": "post_purchase_issue",
    "customer_service": "post_purchase_issue",
    "human_agent": "post_purchase_issue",
}

# Hinglish retail dataset labels
HINGLISH_TO_INTENT: dict[str, str] = {
    "product_availability": "pre_purchase",
    "product_information": "pre_purchase",
    "discount_query": "pre_purchase",
    "track_order": "order_status",
    "cancel_order": "post_purchase_issue",
    "exchange_product": "post_purchase_issue",
    "refund_status": "post_purchase_issue",
    "delivery_complaint": "post_purchase_issue",
    "damaged_item": "post_purchase_issue",
    "wrong_item": "post_purchase_issue",
    "return_request": "post_purchase_issue",
    "payment_issue": "post_purchase_issue",
    "other": "non_customer_noise",
}

NOISE_EXAMPLES = [
    "ok",
    "okay",
    "thanks",
    "thank you",
    "thx",
    "👍",
    "🙏",
    "hi",
    "hello",
    "hey",
    "hii",
    "good morning",
    "good evening",
    "lol",
    "haha",
    "???",
    "...",
    "test",
    "testing",
    "asdf",
    "spam offer click here free iphone",
    "Congratulations you won a lottery prize claim now",
    "Buy followers cheap!!!",
    "Unsubscribe me",
    "k",
    "kk",
    "hmm",
    "nice",
    "cool",
    "👍👍👍",
    "Sticker",
    "Photo",
    "Voice message",
    "Unsupported message type",
    "yes",
    "no",
    "haan",
    "nahi",
    "ok bro",
    "done",
    "noted",
    "👍 ok",
]

PRE_PURCHASE_EXAMPLES = [
    "Do you have this in size M?",
    "Is this available in black?",
    "What is the price of this product?",
    "Do you ship to Bangalore?",
    "Is COD available?",
    "Can I get this in XL?",
    "Stock available hai kya?",
    "Size chart share karo",
    "Kitne ka hai ye?",
    "Any discount on this?",
    "Is this waterproof?",
    "Material kya hai?",
    "Do you have other colours?",
    "When will this be back in stock?",
    "Can I order 2 pieces?",
    "Is this original?",
    "Delivery charges kitne hain before order?",
    "Product details please",
    "Compatible with iPhone 15?",
    "Looking to buy, need recommendation",
]

ORDER_STATUS_EXAMPLES = [
    "Where is my order?",
    "Track my shipment",
    "Order kab deliver hoga?",
    "Tracking link bhejo",
    "Still not delivered, status?",
    "AWB number se track karo",
    "Expected delivery date?",
    "Courier ne pick up kiya kya?",
    "My order is delayed",
    "Out for delivery hai kya?",
]
